### ISSUE TITLE
Change in function arguments / type declaration 

### ISSUE THREAD

**Issue by steffenkaminski** [spine-tools/Spine-Database-API#138]
Hi, 

on ELDEST project we still use the spinedb_api directly from python. 

coming form version 08cc851f80ad0de44f8c021c6b3ffd4deaf996d3 from 23/09/2020 it seems that input arguments of at least:

- get_or_add_parameter_definition (subfunction of sqalchemie expects a  bytes-like object instead of a string)
- add_relationships (add_relationship.py line 62, AttributeError: 'NoneType' object has no attribute 'name')

has changed to the master branch. I was trying to update our interface to the newest version.

Would it be possible to provide some more information about the type-definition of the API functions?

**Comment by soininen** [comment]
I guess the bytes-like object issue in `get_or_add_parameter_definition()` stems from the fact that we now store parameter (default) values as binary blobs instead of strings as in the future we are planning to move from JSON to some binary format for storing the values. To make client code more robust against such changes it is recommended to use `to_database()` (see `parameter_value.py`) to convert values from plain Python types to their database representations. It has a companion function `from_database()`.

I couldn't find the `add_relationships()` function mentioned in issue's description. We don't have `add_relationship.py` file in spinedb_api at all so I'm not sure about that problem.

We do have some API documentation available as docstrings in the `.py` files. These can be compiled to a html reference using the `bin\build_doc.bat` (Windows) or `bin/build_doc.py` (*NIX) scripts. The documentation clearly has room for improvements, though.
