### ISSUE TITLE
Improvements in parameter value lists

### ISSUE THREAD

**Issue by manuelma** [spine-tools/Spine-Database-API#151]
I believe the `parameter_value_list` table is poorly designed, we should have an additional table only with the list values. At the moment it looks like this:

`parameter_value_list`
| id | name | value_index | value |
| --- | --- | --- | --- |
| 1 | booleans | 0 | true |
| 1 | booleans | 1 | false |

So as you see, two records (or as many values are in the list) have the same id, and the name needs to be replicated too -- the primary key is (id, value_index).

I would like to do it like this:

`parameter_value_list`
| id | name | 
| --- | --- |
| 1 | booleans |
| 2 | important_dates |

`list_value`
| id | list_id | index | value |  type |
| --- | --- | --- | --- | --- |
| 1 | 1 | 0 | true | null |
| 2 | 1 | 1 | false | null |
| 3 | 2 | 0 | {"value": "2021-12-25T00:00"} | date_time |
| 4 | 2 | 1 | "my_birthday" | null |

So in addition to splitting the table to avoid repetition, we add the `type` column.

**Comment by jkiviluo** [comment]
You're right. However, does the `parameter_value_list_value` need it's own id? Isn't [list_id, index] a sufficient key? Or can there be multiple items with the same [list_id, index]?

**Comment by manuelma** [comment]
It doesn't need it but it's cool to have it for consistency with the other tables. For example, in toolbox, we want to create dictionaries indexed by the id field and it would be annoying to have an exception for parameter_value_list_value

**Comment by DillonJ** [comment]
Hi @manuelma 

I feel it would add a lot more functionality if you had this instead:


I would like to do it like this:

`parameter_value_list`
| id | name | 
| --- | --- |
| 1 | booleans |
| 2 | important_dates |

`parameter_value`
| id | value |  type |
| --- | --- | --- | --- | --- |
| 1 | true | null |
| 2 | false | null |
| 3 | {"value": "2021-12-25T00:00"} | date_time |
| 4 | "my_birthday" | null |

`parameter_list_value`
| list_id | value_id |
| --- | --- |
| 1 | 1 |
| 1 | 2 | 
| 2 | 1 | 
| 2 | 2 | 

This way you can use the value independently of the list and we get "symbol" functionality for free - and this can serve as a foundation for more complex functionality

**Comment by soininen** [comment]
> I feel it would add a lot more functionality if you had this instead:

The separate table for values will have a lot of management overhead since we'd need to implement copy-on-write and reference counting mechanisms unless that can somehow be offloaded to the database engine.

**Comment by manuelma** [comment]
> copy-on-write and reference counting mechanisms

I'm not sure what you mean @soininen ? Can you please expand a little bit?

**Comment by soininen** [comment]
> I'm not sure what you mean @soininen ? Can you please expand a little bit?

A separate `parameter_value` table looks nice if you never modify anything. However, since things are editable, we'd need to consider e.g.  the following:

- If you delete a value, is it still used by other lists/future symbols? If yes, we need to keep it in `parameter_value` table. (reference counting)
- If you add a value, does it already exist in `parameter_value`? If yes, then use that, otherwise actually add it.
- If you change a value, is it used by other lists/future symbols? If yes, then you need to create a new value (copy-on-write) or, ideally, check if any of existing values is equal to the changed value.

I'm just trying to say that implementing all that extra logic in `spinedb_api` has its development and maintanance overhead and I'm not sure if the benefits of separate `parameter_value` table are worth it. I'm currently working on `metadata` which suffers from exactly the same design (name-value pairs are in a "shared" table) and I cannot say I am entirely happy with it.

**Comment by manuelma** [comment]
Ok, thank you for the explanation. I agree with you that we don't want to have anything like that. What we want (I think) is a table of 'free values' (let's not call it `parameter_value` since we already have a table called that) that the *user* can manage and then reference both from `parameter_value` and the recently added `list_value` tables. It's not something that *we* need to manage behing the scenes.

**Comment by manuelma** [comment]
So:
- if the user deletes a row from `parameter_value`, nothing happens to `free_value`
- if the user adds a row to `parameter_value` where the `value` field happens to be in `free_value`, we don't do any linking. Linking is done explicitely via a new `type` called something appropriate (like "reference" or something).
- if the user modifies a row in `parameter_value`, then again, nothing happens to `free_value`.

So in sum, `free_value` is an independent table where the use can put e.g. long time series that need to go into multiple `parameter_value` rows - to save space, instead of duplicating the time series in each of these rows, we just have a reference to the `free_value` row where that time series uniquely lives.

**Comment by manuelma** [comment]
And about metadata, I think we could try something similar instead of the nightmare you're dealing with?

**Comment by soininen** [comment]
The `free_value` table approach doesn't sound too bad, at least from development perspective.

> And about metadata, I think we could try something similar instead of the nightmare you're dealing with?

Maybe. Makes me wonder if making users to manage a `free_metadata` (or similar) table and links to it by hand is too much to ask. Maybe it isn't.

**Comment by DillonJ** [comment]
So what if we had instead:

`parameter_value`
| id | name | value | type |
| --- | --- | --- | --- |
| 1 | boolean_true | true | null |
| 2 | boolean_false | null |
| 3 | model_start_date | {"value": "2021-12-25T00:00"} | date_time |
| 4 | "significant_event" | "my_birthday" | null |

This way, the user will normally see a reference to the free value rather than the value itself. This means that it is not relevant if the value itself is already present as another free value or indeed another free list value - it still might change differently to this other value that at the moment has the same value but might not always.

**Comment by soininen** [comment]
FYI: I dragged myself kicking and screaming to implement reference counting and copy-on-write for entity and value metadata (not yet merged to master) so lets keep the metadata tables as they are for now.

**Comment by jkiviluo** [comment]
The original issue has been implemented. The "reference" or "symbol" functionality will become possible with the parameter type changes in v0.8.
